<?php
session_start();

// ==========================================
// ADMIN CONFIGURATION
// ==========================================

// 1. अपना एडमिन पासवर्ड यहाँ सेट करें (इसे बदल लें)
$admin_password = "SAURABHXMOD"; 

// 2. वही फाइल नाम लिखें जो index.php में है
$key_file = "keys.txt"; 

// ==========================================
// LOGIC
// ==========================================

// Logout Logic
if (isset($_GET['logout'])) {
    session_destroy();
    header("Location: admin.php");
    exit();
}

// Login Logic
if (isset($_POST['password'])) {
    if ($_POST['password'] === $admin_password) {
        $_SESSION['logged_in'] = true;
    } else {
        $error = "Galat Password!";
    }
}

// Check Login Status
$is_logged_in = isset($_SESSION['logged_in']) && $_SESSION['logged_in'] === true;

// Generate Key Logic (Only if logged in)
$new_key = "";
if ($is_logged_in && isset($_POST['generate_key'])) {
    
    // Random Key Generator
    function generateRandomString($length = 4) {
        return strtoupper(substr(bin2hex(random_bytes($length)), 0, $length));
    }
    
    // Custom Prefix Key
    $new_key = "ADMIN-" . generateRandomString(4) . "-" . generateRandomString(4) . "-" . generateRandomString(4);
    
    // Save to file
    $entry = $new_key . " | Generated by Admin | Date: " . date("Y-m-d H:i:s") . "\n";
    file_put_contents($key_file, $entry, FILE_APPEND);
}

// Read Existing Keys
$all_keys = "";
if (file_exists($key_file)) {
    $all_keys = file_get_contents($key_file);
}

?>

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Admin Panel - Key Manager</title>
    <style>
        body {
            background-color: #0d0d0d;
            color: #fff;
            font-family: monospace;
            display: flex;
            justify-content: center;
            padding-top: 50px;
        }
        .container {
            width: 90%;
            max-width: 600px;
            background: #1a1a1a;
            padding: 20px;
            border: 1px solid #333;
            border-radius: 8px;
            box-shadow: 0 0 15px rgba(255, 0, 0, 0.2);
        }
        h2 { color: #ff3333; text-align: center; }
        input[type="password"] {
            width: 70%;
            padding: 10px;
            background: #000;
            border: 1px solid #444;
            color: #fff;
        }
        button {
            padding: 10px 20px;
            background: #ff3333;
            color: white;
            border: none;
            cursor: pointer;
            font-weight: bold;
        }
        button:hover { background: #cc0000; }
        .key-box {
            background: #000;
            border: 1px dashed #444;
            padding: 10px;
            margin: 10px 0;
            color: #00ff00;
            font-size: 18px;
            word-break: break-all;
        }
        .list-box {
            background: #000;
            border: 1px solid #333;
            padding: 10px;
            height: 300px;
            overflow-y: scroll;
            font-size: 12px;
            white-space: pre-wrap;
            color: #aaa;
        }
        .logout { float: right; color: #888; text-decoration: none; font-size: 12px; }
    </style>
</head>
<body>

<div class="container">
    
    <?php if (!$is_logged_in): ?>
        <h2>ADMIN LOGIN</h2>
        <?php if(isset($error)) echo "<p style='color:red; text-align:center;'>$error</p>"; ?>
        <form method="POST" style="text-align: center;">
            <input type="password" name="password" placeholder="Enter Admin Password" required>
            <button type="submit">Login</button>
        </form>

    <?php else: ?>
        <a href="?logout=true" class="logout">[LOGOUT]</a>
        <h2>KEY MANAGER</h2>
        
        <div style="text-align: center; border-bottom: 1px solid #333; padding-bottom: 20px;">
            <form method="POST">
                <button type="submit" name="generate_key" style="width: 100%; background: #008000;">+ GENERATE NEW KEY</button>
            </form>
            
            <?php if ($new_key): ?>
                <p>New Key Created:</p>
                <div class="key-box"><?php echo $new_key; ?></div>
            <?php endif; ?>
        </div>

        <h3>Active Keys Database:</h3>
        <div class="list-box"><?php echo $all_keys ?: "No keys found."; ?></div>
        
    <?php endif; ?>

</div>

</body>
</html>
